spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cv-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: ERROR
    org.apache.kafka: WARN